services:
  - type: web
    name: BookStation
    env: python
    plan: free
    # buildCommand: "build.sh"
    startCommand: "gunicorn BookStation.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookstore database
          property: connectionString
      - key: SECRET_KEY
        value: your-django-secret-key
        envVars:
      - key: CLOUDINARY_CLOUD_NAME
        value: your_cloud_name
      - key: CLOUDINARY_API_KEY
        value: your_api_key
      - key: CLOUDINARY_API_SECRET
        value: your_api_secret

