# Generated by Django 5.2.1 on 2025-06-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
