# Generated by Django 4.2.7 on 2025-06-11 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã khuyến mãi')),
                ('name', models.CharField(max_length=200, verbose_name='Tên khuyến mãi')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('promotion_type', models.CharField(choices=[('public', 'Công khai'), ('private', 'Riêng tư')], default='public', max_length=10, verbose_name='Loại khuyến mãi')),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm'), ('fixed', 'Số tiền cố định')], max_length=10, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá trị giảm')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số tiền giảm tối đa')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Đơn hàng tối thiểu')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('usage_limit', models.IntegerField(blank=True, null=True, verbose_name='Giới hạn sử dụng')),
                ('usage_limit_per_user', models.IntegerField(default=1, verbose_name='Giới hạn sử dụng mỗi người')),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Không hoạt động'), ('expired', 'Hết hạn')], default='active', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('applicable_books', models.ManyToManyField(blank=True, to='books.book', verbose_name='Sách áp dụng')),
                ('applicable_categories', models.ManyToManyField(blank=True, to='books.category', verbose_name='Danh mục áp dụng')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Khuyến mãi',
                'verbose_name_plural': 'Khuyến mãi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã đơn hàng')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền giảm')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian sử dụng')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion', verbose_name='Khuyến mãi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử sử dụng khuyến mãi',
                'verbose_name_plural': 'Lịch sử sử dụng khuyến mãi',
                'ordering': ['-used_at'],
            },
        ),
    ]
