name: Django CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Django settings
        run: |
          python BookStation/manage.py check

      - name: Run Django tests
        run: |
          python BookStation/manage.py test

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 BookStation/

      - name: Security check with bandit
        run: |
          pip install bandit
          bandit -r BookStation/
